//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.02 at 03:10:45 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.flamexander.com/spring/ws/wsproducts", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.geekbrains.april.market.wsproducts;
